/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jkp.as.forms;

import com.jkp.as.objects.SchoolClass;
import com.jkp.as.objects.Section;
import com.jkp.as.utils.DB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author dpunk12
 */
public class AddClass extends javax.swing.JDialog {

    /**
     * Creates new form AddStudent
     */
    public AddClass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        initTeachersCombobox();
        initSectionsCombobox();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddClass = new javax.swing.JButton();
        cmbTeacher = new javax.swing.JComboBox();
        cmbSection = new javax.swing.JComboBox();
        txtTimeOut = new javax.swing.JTextField();
        txtTimeIn = new javax.swing.JTextField();
        txtClassname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setText("Teacher:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("Section:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Time In:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Time Out:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Class Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        btnAddClass.setBackground(new java.awt.Color(172, 203, 255));
        btnAddClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Add_50px.png"))); // NOI18N
        btnAddClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClassActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 70, 60));

        cmbTeacher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 210, 30));

        cmbSection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 210, 30));
        getContentPane().add(txtTimeOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 210, 30));
        getContentPane().add(txtTimeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 210, 30));
        getContentPane().add(txtClassname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD CLASS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 0, 24))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 310, 330));

        jLabel6.setBackground(new java.awt.Color(172, 203, 255));
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClassActionPerformed
        addClass();
    }//GEN-LAST:event_btnAddClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddClass dialog = new AddClass(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClass;
    private javax.swing.JComboBox cmbSection;
    private javax.swing.JComboBox cmbTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtClassname;
    private javax.swing.JTextField txtTimeIn;
    private javax.swing.JTextField txtTimeOut;
    // End of variables declaration//GEN-END:variables
    
    private HashMap<String,Integer> teachers;
    private HashMap<String,Integer> sections;
    
    private void addClass(){
        SchoolClass s = new SchoolClass();
        s.setTeacherid(teachers.get(cmbTeacher.getSelectedItem().toString()));
        s.setSectionid(sections.get(cmbSection.getSelectedItem().toString()));
        s.setTimein(txtTimeIn.getText());
        s.setTimeout(txtTimeOut.getText());
        s.setClassname(txtClassname.getText());
        
        try{
            s.addToDatabase();
            JOptionPane.showMessageDialog(null, "Class Successfully Added!");
            dispose();
        }catch(SQLException e){e.printStackTrace();}
    }
    
    private void initTeachersCombobox(){
        try{
        teachers = new HashMap<>();
        cmbTeacher.removeAllItems();
        ResultSet rs = DB.query("SELECT * FROM teacher_fullname");
        while(rs.next()){
            int id = rs.getInt(1);
            String name = rs.getString(2);
            teachers.put(name,id);
            cmbTeacher.addItem(name);
        }
            
        }catch(SQLException e){e.printStackTrace();}
    }
    
    private void initSectionsCombobox(){
        try{
        sections = new HashMap<>();
        cmbSection.removeAllItems();
        ResultSet rs = DB.query("SELECT sectionid,sectionname FROM section");
        while(rs.next()){
            int id = rs.getInt(1);
            String name = rs.getString(2);
            sections.put(name,id);
            cmbSection.addItem(name);
        }
            
        }catch(SQLException e){e.printStackTrace();}
    }

}
