/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jkp.as.forms;

import com.jkp.as.objects.Enroll;
import com.jkp.as.utils.DB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dpunk12
 */
public class EnrollStudents extends javax.swing.JFrame {

    /**
     * Creates new form EnrollStudent
     */
    public EnrollStudents() {
        initComponents();
        
        refreshStudenttsTable();
        initSectionsTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSections = new javax.swing.JTable();
        btnEnroll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearchStudent = new javax.swing.JTextField();
        txtSearchSection = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStudents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblStudents);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 247, 389));

        tblSections.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSections.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblSections);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 86, 247, 389));

        btnEnroll.setText("Enroll Student");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 509, 500, 38));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enroll Student");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 500, 69));
        getContentPane().add(txtSearchStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 478, 247, -1));
        getContentPane().add(txtSearchSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 478, 247, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 0, -1, -1));

        jLabel3.setBackground(new java.awt.Color(172, 203, 255));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        enroll();
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        initSectionsTable();
        refreshStudenttsTable();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrollStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrollStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrollStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrollStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSections;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtSearchSection;
    private javax.swing.JTextField txtSearchStudent;
    // End of variables declaration//GEN-END:variables
    
    private HashMap<String,String> students;
    private HashMap<String,Integer> sections;
    
    private void refreshStudenttsTable(){
        try{
            students = new HashMap<>();
            ResultSet rs = DB.query("SELECT * FROM student_fullname LEFT JOIN enroll ON(studentid=lrn) WHERE studentid IS NULL;");
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Students");
            while(rs.next()){
                String lrn = rs.getString(1);
                String name = rs.getString(2);
                
                students.put(name, lrn);
                model.addRow(new String[]{name});
            }
            tblStudents.setModel(model);
                    
                    
        }catch(SQLException e){e.printStackTrace();}
    }
    
    
    private void initSectionsTable(){
        try{
            sections = new HashMap<>();
            ResultSet rs = DB.query("SELECT sectionid,sectionname FROM section");
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Sections");
            while(rs.next()){
                int sectionid = rs.getInt(1);
                String name = rs.getString(2);
                
                sections.put(name, sectionid);
                model.addRow(new String[]{name});
            }
            tblSections.setModel(model);
                    
                    
        }catch(SQLException e){e.printStackTrace();}
    }
    
    private void enroll(){
        Enroll e = new Enroll();
        e.setStudentid(students.get(tblStudents.getValueAt(tblStudents.getSelectedRow(),0).toString()));
        e.setSectionid(sections.get(tblSections.getValueAt(tblSections.getSelectedRow(),0).toString()));
        
        
        try{
            e.addToDatabase();
            JOptionPane.showMessageDialog(null, "Successfully Enrolled Student!");
        }catch(SQLException ex){ex.printStackTrace();}
    }
    
    
    
}
