/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jkp.as.forms;

import com.jkp.as.objects.Attendance;
import com.jkp.as.utils.DB;
import java.sql.SQLException;

/**
 *
 * @author dpunk12
 */
public class SetAttendance extends javax.swing.JDialog {

    /**
     * Creates new form SetAttendance
     */
    
    
    private Attendance attendance;
    private String studentname;
    public SetAttendance(Attendance attendance,String studentname,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        this.attendance = attendance;
        this.studentname = studentname;
        
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        lblStudentName.setText(studentname);
        if(attendance.getAttend()==0){
            rdPresent.setSelected(true);
        }else if(attendance.getAttend()==1){
            rdAbsent.setSelected(true);
        }else if(attendance.getAttend()==2){
            rdExcuse.setSelected(true);
        }
        txtNote.setText(attendance.getNote());
        
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdPresent = new javax.swing.JRadioButton();
        rdAbsent = new javax.swing.JRadioButton();
        rdExcuse = new javax.swing.JRadioButton();
        btnAccept = new javax.swing.JButton();
        chkTardy = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name:");

        lblStudentName.setText("Firstname M. Lastname");

        jLabel3.setText("Note:");

        rdgrp.add(rdPresent);
        rdPresent.setText("Present");

        rdgrp.add(rdAbsent);
        rdAbsent.setText("Absent");

        rdgrp.add(rdExcuse);
        rdExcuse.setText("Excuse");

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        chkTardy.setText("Tardy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkTardy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAccept))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdPresent)
                                .addGap(18, 18, 18)
                                .addComponent(rdAbsent)
                                .addGap(18, 18, 18)
                                .addComponent(rdExcuse))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNote)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblStudentName)
                    .addComponent(rdPresent)
                    .addComponent(rdAbsent)
                    .addComponent(rdExcuse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(chkTardy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        update();
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JCheckBox chkTardy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JRadioButton rdAbsent;
    private javax.swing.JRadioButton rdExcuse;
    private javax.swing.JRadioButton rdPresent;
    private javax.swing.ButtonGroup rdgrp;
    private javax.swing.JTextField txtNote;
    // End of variables declaration//GEN-END:variables
    
    
    
    private void update(){
        try{
            int attend = 0;
            if(rdPresent.isSelected()){
                attend=0;
            }else if(rdAbsent.isSelected()){
                attend=1;
            }else if(rdExcuse.isSelected()){
                attend=2;
            }
            DB.query("UPDATE attendance SET attend="+attend+", note='"+txtNote.getText()+"', tardy="+String.valueOf(chkTardy.isSelected())+" WHERE attendanceid="+attendance.getAttendanceid(), true);
            dispose();
        }catch(SQLException e){e.printStackTrace();}
    }

}
